services:
  db:
    container_name: mysql
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: shiftninja
      MYSQL_USER: technologyinnovation
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - shiftninja
    restart: unless-stopped

  backend:
    container_name: sn_backend
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - shiftninja
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    container_name: sn_frontend
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    volumes:
      - ./Frontend/nginx-config:/etc/nginx/conf.d
    ports:
      - "5000:80"
    networks:
      - shiftninja
    depends_on:
      - backend
    restart: unless-stopped

networks:
  shiftninja:
    driver: bridge

volumes:
  mysql-data:
    driver: local